version: "3.7"
services:
  redis_db:
    image: redis
    command: redis-server --appendonly yes
    restart: unless-stopped
    ports:
      - "127.0.0.1:6379:6379"
    volumes:
      - /docker/redis-data:/data
  bot:
    image: docker.pkg.github.com/notmeta/osrs.cx/osrscx:0.3.1
    restart: unless-stopped
    links:
      - redis_db
    environment:
      #      - DG_TOKEN=
      - REDIS_IP=redis_db
